Add support for configurable S3 storage class
MeltwaterArchive/elasticsearch-cloud-aws-retry-fix pull request #3
Opened 2019-09-09 09:18 UTC by tfardig

2019-09-09 15:14 UTC, tfardig commented on src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java
> +            return "s3-eu-west-2.amazonaws.com";
Needed to add support for the London region for test purposes, might as well keep it.

2019-09-13 07:50 UTC, SiXoS requested changes

2019-09-13 07:50 UTC, SiXoS commented on pom.xml
> +    <version>2.7.1-retry-fix-storage-class</version>
I'm assuming that you'll change this on merge

2019-09-13 07:50 UTC, SiXoS commented on src/main/java/org/elasticsearch/cloud/aws/blobstore/DefaultS3OutputStream.java
> +            if (parts.length > 0) {
This is not needed and leads to confusion. Remove it.

2019-09-24 11:55 UTC, merged